from models.base_model.ClsBaseVO import ClsBaseVO


class ClsBIVO_2002_12_14_to_2100_01_01(ClsBaseVO):
    def __init__(self, file_path: str, record):
        super().__init__(file_path, record)

        self.AZIPOS: float = record[1]
        self.ELEPOS: float = record[2]
        self.AZIERR: float = record[3]
        self.ELEERR: float = record[4]
        self.ADC_1: int = record[5]
        self.ADC_2: int = record[6]
        self.ADC_3: int = record[7]
        self.ADC_4: int = record[8]
        self.ADC_5: int = record[9]
        self.ADC_6: int = record[10]
        self.SIGMA_1: float = record[11]
        self.SIGMA_2: float = record[12]
        self.SIGMA_3: float = record[13]
        self.SIGMA_4: float = record[14]
        self.SIGMA_5: float = record[15]
        self.SIGMA_6: float = record[16]
        self.GPS_STATUS: int = record[17]
        self.ACQ_GAIN: int = record[18]
        self.TARGET: int = record[19]
        self.OPMODE: int = record[20]
        self.OFF_1: int = record[21]
        self.OFF_2: int = record[22]
        self.OFF_3: int = record[23]
        self.OFF_4: int = record[24]
        self.OFF_5: int = record[25]
        self.OFF_6: int = record[26]
        self.HOT_TEMP: float = record[27]
        self.AMB_TEMP: float = record[28]
        self.OPT_TEMP: float = record[29]
        self.IF_BOARD_TEMP: float = record[30]
        self.RADOME_TEMP: float = record[31]
        self.HUMIDITY: float = record[32]
        self.TEMPERATURE: float = record[33]
        self.OPAC_210: float = record[34]
        self.OPAC_405: float = record[35]
        self.ELEVATION: float = record[36]
        self.PRESSURE: float = record[37]
        self.BURST: int = record[38]
        self.ERRORS: int = record[39]
